/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-02-14 08:07:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.newlecture.jspweb.entity.NoticeView;
import com.newlecture.jspweb.dao.jdbc.JdbcNoticeDao;
import com.newlecture.jspweb.entity.Notice;
import java.util.List;
import com.newlecture.jspweb.dao.NoticeDao;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.newlecture.jspweb.dao.jdbc.JdbcNoticeDao");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("com.newlecture.jspweb.entity.NoticeView");
    _jspx_imports_classes.add("com.newlecture.jspweb.entity.Notice");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("com.newlecture.jspweb.dao.NoticeDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
	
		NoticeDao noticeDao = new JdbcNoticeDao();
		List<NoticeView> list = noticeDao.getList();
	
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"../../css/style.css\" type=\"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t/* var list = [\r\n");
      out.write("\t\t{kor:30, eng:40, math:60},\r\n");
      out.write("\t\t{kor:10, eng:70, math:90},\r\n");
      out.write("\t\t{kor:40, eng:60, math:20}\r\n");
      out.write("\t];\r\n");
      out.write("\t\r\n");
      out.write("\talert(list[1].kor); */\r\n");
      out.write("\t\r\n");
      out.write("\t/* var exam = {};\r\n");
      out.write("\texam.kor=30;\r\n");
      out.write("\texam.eng=40;\r\n");
      out.write("\texam.math=\"수학\";\r\n");
      out.write("\t\r\n");
      out.write("\talert(exam.kor + exam.eng); */\r\n");
      out.write("\t\r\n");
      out.write("\t//alert(\"Hello Javascript\");\r\n");
      out.write("</script>\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"root-container\">\r\n");
      out.write("\t\t\t<h1 id=\"logo\">\r\n");
      out.write("\t\t\t<img alt=\"뉴렉처 온라인\" src=\"../../images/logo.png\">\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t<h1 class=\"hidden\">헤더</h1>\r\n");
      out.write("\t\t\t<nav class=\"hor-menu main-menu first-pad-none\">\r\n");
      out.write("\t\t\t\t<h1 class=\"hidden\">메인메뉴</h1>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">학습가이드</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">뉴렉과정</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">강좌선택</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<section>\r\n");
      out.write("\t\t\t\t<h1 class=\"hidden\">강좌검색 폼</h1>\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend class=\"hidden\">검색필드</legend>\r\n");
      out.write("\t\t\t\t\t\t<label>과정검색</label> <input type=\"text\" /> \r\n");
      out.write("\t\t\t\t\t\t<input class=\"btn btn-img btn-search\" type=\"submit\" value=\"검색\" />\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav class=\"hor-menu member-menu first-pad-none\">\r\n");
      out.write("\t\t\t\t<h1>회원 메뉴</h1>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>HOME</li>\r\n");
      out.write("\t\t\t\t\t<li>로그인</li>\r\n");
      out.write("\t\t\t\t\t<li>회원가입</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav class=\"hor-menu member-menu first-pad-none my-menu\">\r\n");
      out.write("\t\t\t\t<h1>간편 메뉴</h1>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><img alt=\"마이페이지\" src=\"../../images/txt-mypage.png\"></li>\r\n");
      out.write("\t\t\t\t\t<li><img alt=\"고객센터\" src=\"../../images/txt-customer.png\"></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- ----------visual 시작------------------------------------------------------ -->\r\n");
      out.write("\t<div id=\"visual\">\r\n");
      out.write("\t\t<div class=\"root-container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"body\">\r\n");
      out.write("\t\t<div class=\"root-container clear-fix\">\r\n");
      out.write("\t\t\t<!-- ----------aside 시작------------------------------------------------------ -->\r\n");
      out.write("\t\t\t<aside id=\"aside\">\r\n");
      out.write("\t\t\t\t<h1>고객센터</h1>\r\n");
      out.write("\t\t\t\t<nav class=\"aside-menu\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"hidden\">고객센터 메뉴</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>공지사항</li>\r\n");
      out.write("\t\t\t\t\t\t<li>1:1고객문의</li>\r\n");
      out.write("\t\t\t\t\t\t<li>학습안내</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t<h1>추천사이트</h1>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>앤서이즈</li>\r\n");
      out.write("\t\t\t\t\t\t<li>W3C</li>\r\n");
      out.write("\t\t\t\t\t\t<li>마이크로소프트</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</aside>\r\n");
      out.write("\t\t\t<!-- ----------main 시작------------------------------------------------------ -->\r\n");
      out.write("\t\t\t<main id=\"main\">\r\n");
      out.write("\t\t\t<section>\r\n");
      out.write("\t\t\t\t<h1 class=\"title\">공지사항</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"hidden\">경로</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>home</li>\r\n");
      out.write("\t\t\t\t\t\t<li>고객센터</li>\r\n");
      out.write("\t\t\t\t\t\t<li>공지사항</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"hidden\">공지사항 검색 폼</h1>\r\n");
      out.write("\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t<label>검색어</label><input type=\"text\" /> <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-text btn-default\" type=\"submit\" value=\"검색\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"hidden\">공지사항 검색 목록</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"width-sm\">번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"width-ex\">제목</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"width-md\">작성자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"width-md\">작성일</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"width-sm\">조회수</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
for(NoticeView n : list) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"width-sm\">");
      out.print(n.getId() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"width-ex align-left text-indent text-ellipsis\"><a href=\"\"><sapn class=\"color-notice\">");
      out.print(n.getTitle() );
      out.write("</sapn></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"width-md\">");
      out.print(n.getWriterName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"width-md\">2017-12-18</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"width-sm\">59</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t<!-- ------------------------------------------------------------------------------------------- -->\t\r\n");
      out.write("\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"hidden\">공지사항 검색 목록</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"thead\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"td width-sm\">번호</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"td width-ex\">제목</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"td width-md\">작성자</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"td width-md\">작성일</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"td width-sm\">조회수</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tbody\">\r\n");
      out.write("\t\t\t\t\t\t");
for(NoticeView n : list) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tr\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"td width-sm\">");
      out.print(n.getId() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"td width-ex align-left text-indent text-ellipsis\"><a href=\"\"><sapn class=\"color-notice\">");
      out.print(n.getTitle() );
      out.write("</sapn></a></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"td width-md\">");
      out.print(n.getWriterId() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"td width-md\">2017-12-18</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"td width-sm\">59</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div>1/1 pages</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"reg\" class=\"button btn-text default-button\">글쓰기 버튼</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"reg\" class=\"btn btn-text cancel-button\">테스트</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>이전1다음</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t</main>\r\n");
      out.write("\t\t<!-- <div style=\"clear:left;\"></div> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t<div class=\"root-container\">\r\n");
      out.write("\t\t\t<!-- 회사정보\r\n");
      out.write("\t주소서울특별시 마포구 토정로35길 11, 5층 266호(용강동, 인우빌딩)관리자메일admin@newlecture.com사업자 등록번호132-18-46763 통신 판매업 신고제 2013-서울강동-0969 호 상호뉴렉처대표박용우전화번호070-4206-4084 [죄송합니다. 당분간 문의내용은 고개센터 메뉴에서 1:1 문의를 이용해주시기 바랍니다]\r\n");
      out.write("\tCopyright ⓒ newlecture.com 2012-2014 All Right Reserved. Contact admin@newlecture.com for more information -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
